#!/usr/bin/env python3
# Copyright (c) 2026 Compute Field Lab, LLC, Abu-Dhabi. All rights reserved.
"""Generate the public Machine API index without importing heavy dependencies."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/reference/python-api.md"


def signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    return f"{prefix}def {node.name}({ast.unparse(node.args)})"


def summary(node: ast.AST) -> str:
    text = ast.get_docstring(node, clean=True) or ""
    return text.split("\n\n", 1)[0].replace("\n", " ")


def fallback(name: str) -> str:
    return name.replace("_", " ").capitalize() + "."


def module_section(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    lines = [f"## `{path.relative_to(ROOT)}`", ""]
    if description := summary(tree):
        lines.extend((description, ""))
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            lines.extend((f"### `class {node.name}`", "", summary(node) or fallback(node.name), ""))
            for member in node.body:
                if isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef)) and not member.name.startswith("_"):
                    lines.append(f"- `{signature(member)}` — {summary(member) or fallback(member.name)}")
            lines.append("")
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
            lines.extend((f"### `{signature(node)}`", "", summary(node) or fallback(node.name), ""))
    return lines


def render() -> str:
    lines = [
        "<!-- Generated by tools/generate-python-reference.py; do not edit manually. -->",
        "# Machine Python API",
        "",
        "Generated from source signatures and docstrings without importing the runtime.",
        "",
    ]
    for path in sorted(ROOT.glob("*.py")):
        lines.extend(module_section(path))
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("Python reference is stale; run tools/generate-python-reference.py")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(OUTPUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
